### ISSUE TITLE
iPhone/Mac app

### ISSUE THREAD

**Issue by jayelm** [GleasonK/aMessage#1]
Is there an iPhone/Mac app?? Would love to have this on my Apple devices!!!

**Comment by GleasonK** [comment]
## iMessage

There is as a matter of fact! Unfortunately due to the restrictions of background threads on Apple devices you will be unable to control videos or volume, start playing music, basically manage the rest of your phone from your laptop. With a few simple lines of code aMessage can become a remote cli for your mobile device. My apologies.

_drops mic_

**Comment by GleasonK** [comment]
_picks mic up_ 

Done. aMessage now acts as a media controller.

_drops mic_
